apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-g1jt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-g1jt@sha256:36c3eb673a195c242c08618178e9861d701d65b26e233ea20f4bd3b5b2f35d30
        name: my-nodejs
        resources: {}
status: {}
